INSERT INTO roles (name, permission) VALUES('ROLE_USER','READ:USER,READ:CUSTOMER');
INSERT INTO roles (name, permission) VALUES('ROLE_MANAGER','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER');
INSERT INTO roles (name, permission) VALUES('ROLE_ADMIN','READ:USER,READ:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER');
INSERT INTO roles (name, permission) VALUES('ROLE_SYSADMIN','READ:USER,READ:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,DELETE:USER,DELETE:CUSTOMER');
